---
# tasks file for nokia
- name: Configure hostname
  arista.eos.eos_hostname:
    config:
      hostname: "{{ inventory_hostname }}"

- name: Configure lldp
  arista.eos.eos_lldp:

- name: Configure vlans
  arista.eos.eos_vlans:
    config:
      name: "vlan{{ vlan_id }}"
      state: active
      vlan_id: "{{ vlan_id }}"
  loop: "{{ vlans }}"
  loop_control:
    label: vlan_id

- name: Run verification commands
  arista.eos.eos_command:
    commands:
      - command: show vlans
        output: json
      - command: show lldp neighbours
        output: json
  register: output

- name: Output command output
  ansible.builtin.debug:
    var: "{{ output }}"
